apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: coco
  name: coco-user-bg
  labels:
    app: coco-user-bg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coco-user-bg
  template:
    metadata:
      labels:
        app: coco-user-bg
    spec:
      containers:
        - name: coco-short-link-bg
          image: asia-east1-docker.pkg.dev/aaron-dev-429414/coco-user-bg/test-image:latest-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: grpc-server
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /q/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 30
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:

            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: coco-mongodb-uri
                  key: uri


            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: key

            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/gcp_credentials.json

          volumeMounts:
            - name: gcp-credentials-volume
              mountPath: /etc/gcp
              readOnly: true

      volumes:
        - name: gcp-credentials-volume
          secret:
            secretName: gcp-credentials
            items:
              - key: credentials
                path: gcp_credentials.json


---

apiVersion: v1
kind: Service
metadata:
  name: coco-user-bg
  namespace: coco
  labels:
    app: coco-user-bg
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - name: grpc-server
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: coco-user-bg
